### ISSUE TITLE
Selected background with intellisense widget is a bit off

### ISSUE THREAD

**Issue by Clafouti** [sdras/inbedby7pm#3]
Hi there, first of all thank your for the theme!

I've had this issue with the ```editorSuggestWidget.selectedBackground```(I hope it's not a clash inside my own VSCode settings...).
![image](https://user-images.githubusercontent.com/7141072/94372287-8fd82d80-00fc-11eb-9843-1e69a346006c.png)

 I use #30354A as a replacement but it might not be optimal (not enough contrast).

**Comment by sdras** [comment]
thank you!

**Comment by sdras** [comment]
This should be fixed now with an update! Please feel free to reopen if not.

**Comment by fpigeonjr** [comment]
Thanks Sarah for this new vscode theme, I am also having the same issue and am still seeing the issue on intelli-sense thing.

<img width="992" alt="Screen Shot 2020-09-27 at 6 16 30 PM" src="https://user-images.githubusercontent.com/4629398/94378242-94491a00-00ed-11eb-864f-c5f244e7e84c.png">
.

**Comment by Clafouti** [comment]
@fpigeonjr Are you sure you correctly updated the theme? 
On my end, I can confirm that the updated fixed the issue :)

**Comment by fpigeonjr** [comment]
> @fpigeonjr Are you sure you correctly updated the theme?
> On my end, I can confirm that the updated fixed the issue :)

@clafouti Confirmed after a reboot this issue is resolved and much readable now. Thanks.
